/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ox.Lobby;

import ox.Login.Login;
import javax.swing.JOptionPane;
import org.bson.Document;
import ox.Profile;
import ox.Ranking;

/**
 *
 * @author Jutamas_Soiraya
 */
public class Lobby extends javax.swing.JFrame {

    String user , roomNo , status , num ;
    
    
    /**
     * Creates new form Lobby
     */
    public Lobby() {
        this.setSize(800, 600);  
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lobbyName = new javax.swing.JLabel();
        refresh = new javax.swing.JToggleButton();
        clickRanking = new javax.swing.JToggleButton();
        clickLogout = new javax.swing.JToggleButton();
        clickProfile = new javax.swing.JToggleButton();
        joinRoom1 = new javax.swing.JButton();
        joinRoom2 = new javax.swing.JButton();
        joinRoom3 = new javax.swing.JButton();
        joinRoom4 = new javax.swing.JButton();
        joinRoom5 = new javax.swing.JButton();
        roomStatus1 = new javax.swing.JLabel();
        roomStatus2 = new javax.swing.JLabel();
        roomStatus3 = new javax.swing.JLabel();
        roomStatus4 = new javax.swing.JLabel();
        roomStatus5 = new javax.swing.JLabel();
        roomColor1 = new javax.swing.JLabel();
        roomColor2 = new javax.swing.JLabel();
        roomColor3 = new javax.swing.JLabel();
        roomColor4 = new javax.swing.JLabel();
        roomColor5 = new javax.swing.JLabel();
        roomNo1 = new javax.swing.JLabel();
        roomNo2 = new javax.swing.JLabel();
        roomNo3 = new javax.swing.JLabel();
        roomNo4 = new javax.swing.JLabel();
        roomNo5 = new javax.swing.JLabel();
        roomFrame1 = new javax.swing.JLabel();
        roomFrame2 = new javax.swing.JLabel();
        roomFrame3 = new javax.swing.JLabel();
        roomFrame4 = new javax.swing.JLabel();
        roomFrame5 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lobby");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lobbyName.setFont(new java.awt.Font("SanamDeklenchaya", 1, 36)); // NOI18N
        lobbyName.setForeground(new java.awt.Color(255, 255, 255));
        lobbyName.setText("Lobby");
        lobbyName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lobbyNameMouseClicked(evt);
            }
        });
        getContentPane().add(lobbyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 25, -1, -1));

        refresh.setBackground(new java.awt.Color(255, 255, 255));
        refresh.setFont(new java.awt.Font("SanamDeklenchaya", 1, 14)); // NOI18N
        refresh.setText("Refresh");
        refresh.setPreferredSize(new java.awt.Dimension(90, 32));
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 140, 60));

        clickRanking.setBackground(new java.awt.Color(255, 255, 255));
        clickRanking.setFont(new java.awt.Font("SanamDeklenchaya", 1, 14)); // NOI18N
        clickRanking.setText("Ranking");
        clickRanking.setPreferredSize(new java.awt.Dimension(90, 32));
        clickRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickRankingActionPerformed(evt);
            }
        });
        getContentPane().add(clickRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 140, 60));

        clickLogout.setBackground(new java.awt.Color(255, 255, 255));
        clickLogout.setFont(new java.awt.Font("SanamDeklenchaya", 1, 14)); // NOI18N
        clickLogout.setText("Logout");
        clickLogout.setPreferredSize(new java.awt.Dimension(90, 32));
        clickLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(clickLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 140, 60));

        clickProfile.setBackground(new java.awt.Color(255, 255, 255));
        clickProfile.setFont(new java.awt.Font("SanamDeklenchaya", 1, 14)); // NOI18N
        clickProfile.setText("Profile");
        clickProfile.setPreferredSize(new java.awt.Dimension(90, 32));
        clickProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickProfileActionPerformed(evt);
            }
        });
        getContentPane().add(clickProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 140, 60));

        joinRoom1.setText("Join");
        joinRoom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinRoom1ActionPerformed(evt);
            }
        });
        getContentPane().add(joinRoom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 90, 40));

        joinRoom2.setText("Join");
        joinRoom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinRoom2ActionPerformed(evt);
            }
        });
        getContentPane().add(joinRoom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 90, 40));

        joinRoom3.setText("Join");
        joinRoom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinRoom3ActionPerformed(evt);
            }
        });
        getContentPane().add(joinRoom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 90, 40));

        joinRoom4.setText("Join");
        joinRoom4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinRoom4ActionPerformed(evt);
            }
        });
        getContentPane().add(joinRoom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 90, 40));

        joinRoom5.setText("Join");
        joinRoom5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinRoom5ActionPerformed(evt);
            }
        });
        getContentPane().add(joinRoom5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 90, 40));

        roomStatus1.setBackground(new java.awt.Color(0, 0, 0));
        roomStatus1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        roomStatus1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomStatus1.setText("0/2");
        getContentPane().add(roomStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 60, 20));

        roomStatus2.setBackground(new java.awt.Color(0, 0, 0));
        roomStatus2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        roomStatus2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomStatus2.setText("0/2");
        getContentPane().add(roomStatus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 60, 20));

        roomStatus3.setBackground(new java.awt.Color(0, 0, 0));
        roomStatus3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        roomStatus3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomStatus3.setText("0/2");
        getContentPane().add(roomStatus3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 60, 20));

        roomStatus4.setBackground(new java.awt.Color(0, 0, 0));
        roomStatus4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        roomStatus4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomStatus4.setText("0/2");
        getContentPane().add(roomStatus4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 60, 20));

        roomStatus5.setBackground(new java.awt.Color(0, 0, 0));
        roomStatus5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        roomStatus5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomStatus5.setText("0/2");
        getContentPane().add(roomStatus5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 60, 20));

        roomColor1.setBackground(new java.awt.Color(255, 255, 255));
        roomColor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images.jpeg"))); // NOI18N
        roomColor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(roomColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 200, 40));

        roomColor2.setBackground(new java.awt.Color(255, 255, 255));
        roomColor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images.jpeg"))); // NOI18N
        roomColor2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(roomColor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 200, 40));

        roomColor3.setBackground(new java.awt.Color(255, 255, 255));
        roomColor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images.jpeg"))); // NOI18N
        roomColor3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(roomColor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 200, 40));

        roomColor4.setBackground(new java.awt.Color(255, 255, 255));
        roomColor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images.jpeg"))); // NOI18N
        roomColor4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(roomColor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 200, 40));

        roomColor5.setBackground(new java.awt.Color(255, 255, 255));
        roomColor5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images.jpeg"))); // NOI18N
        roomColor5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(roomColor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 200, 40));

        roomNo1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        roomNo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomNo1.setText("1");
        getContentPane().add(roomNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 30, 40));

        roomNo2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        roomNo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomNo2.setText("2");
        getContentPane().add(roomNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 30, 40));

        roomNo3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        roomNo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomNo3.setText("3");
        getContentPane().add(roomNo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 30, 40));

        roomNo4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        roomNo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomNo4.setText("4");
        getContentPane().add(roomNo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 30, 40));

        roomNo5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        roomNo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomNo5.setText("5");
        getContentPane().add(roomNo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 30, 40));

        roomFrame1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg1.jpg"))); // NOI18N
        roomFrame1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(roomFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 470, 70));

        roomFrame2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg1.jpg"))); // NOI18N
        roomFrame2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(roomFrame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 470, 70));

        roomFrame3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg1.jpg"))); // NOI18N
        roomFrame3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(roomFrame3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 470, 70));

        roomFrame4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg1.jpg"))); // NOI18N
        roomFrame4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(roomFrame4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 470, 70));

        roomFrame5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg1.jpg"))); // NOI18N
        roomFrame5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(roomFrame5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 470, 70));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg-blue.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        loadLobby();
    }//GEN-LAST:event_refreshActionPerformed

    private void clickRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickRankingActionPerformed
        setVisible(false);
        new Ranking().show();
    }//GEN-LAST:event_clickRankingActionPerformed

    private void clickProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickProfileActionPerformed
        setVisible(false);
        new Profile().show();
    }//GEN-LAST:event_clickProfileActionPerformed

    private void clickLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickLogoutActionPerformed
        setVisible(false);
        new Login().show();
    }//GEN-LAST:event_clickLogoutActionPerformed

    private void joinRoom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinRoom1ActionPerformed
        if (checkRoom(1)){
          clickRoom();
        }else{
           JOptionPane.showMessageDialog(null,"room is full"); 
        }
        loadLobby();
    }//GEN-LAST:event_joinRoom1ActionPerformed

    private void joinRoom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinRoom2ActionPerformed
        if (checkRoom(2)){
          clickRoom();
        }else{
           JOptionPane.showMessageDialog(null,"room is full"); 
        }
        loadLobby();
    }//GEN-LAST:event_joinRoom2ActionPerformed

    private void joinRoom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinRoom3ActionPerformed
        if (checkRoom(3)){
          clickRoom();
        }else{
           JOptionPane.showMessageDialog(null,"room is full"); 
        }
        loadLobby();
    }//GEN-LAST:event_joinRoom3ActionPerformed

    private void joinRoom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinRoom4ActionPerformed
        if (checkRoom(4)){
          clickRoom();
        }else{
           JOptionPane.showMessageDialog(null,"room is full"); 
        }
        loadLobby();
    }//GEN-LAST:event_joinRoom4ActionPerformed

    private void joinRoom5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinRoom5ActionPerformed
        if (checkRoom(5)){
          clickRoom();
        }else{
           JOptionPane.showMessageDialog(null,"room is full"); 
        }
        loadLobby();
    }//GEN-LAST:event_joinRoom5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadLobby();
    }//GEN-LAST:event_formWindowOpened

    private void lobbyNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lobbyNameMouseClicked
        removePlayer();
        loadLobby();
    }//GEN-LAST:event_lobbyNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JToggleButton clickLogout;
    private javax.swing.JToggleButton clickProfile;
    private javax.swing.JToggleButton clickRanking;
    private javax.swing.JButton joinRoom1;
    private javax.swing.JButton joinRoom2;
    private javax.swing.JButton joinRoom3;
    private javax.swing.JButton joinRoom4;
    private javax.swing.JButton joinRoom5;
    private javax.swing.JLabel lobbyName;
    private javax.swing.JToggleButton refresh;
    private javax.swing.JLabel roomColor1;
    private javax.swing.JLabel roomColor2;
    private javax.swing.JLabel roomColor3;
    private javax.swing.JLabel roomColor4;
    private javax.swing.JLabel roomColor5;
    private javax.swing.JLabel roomFrame1;
    private javax.swing.JLabel roomFrame2;
    private javax.swing.JLabel roomFrame3;
    private javax.swing.JLabel roomFrame4;
    private javax.swing.JLabel roomFrame5;
    private javax.swing.JLabel roomNo1;
    private javax.swing.JLabel roomNo2;
    private javax.swing.JLabel roomNo3;
    private javax.swing.JLabel roomNo4;
    private javax.swing.JLabel roomNo5;
    private javax.swing.JLabel roomStatus1;
    private javax.swing.JLabel roomStatus2;
    private javax.swing.JLabel roomStatus3;
    private javax.swing.JLabel roomStatus4;
    private javax.swing.JLabel roomStatus5;
    // End of variables declaration//GEN-END:variables

    void loadLobby(){
    
        for (int i = 1 ; i <= 5 ; i++ ){
        num = Integer.toString(i);
        roomNo = "room" + num;
        
        status = LobbyService.loadLobbyStatus(roomNo);
          
          if (i == 1){
              roomStatus1.setText(status +"/2");
            
          }else if (i == 2){
              roomStatus2.setText(status +"/2");
          }else if (i == 3){
              roomStatus3.setText(status +"/2");
          }else if (i == 4){
              roomStatus4.setText(status +"/2");
          }else if (i == 5){
              roomStatus5.setText(status +"/2");
          }
          
          if (roomStatus1.getText().equals("2/2")){
            roomColor1.setIcon(new javax.swing.ImageIcon(".\\src\\Image\\red.jpg"));  
          }else{
             roomColor1.setIcon(new javax.swing.ImageIcon(".\\src\\Image\\images.jpeg"));   
          }
          if (roomStatus2.getText().equals("2/2")){
              roomColor2.setIcon(new javax.swing.ImageIcon(".\\src\\Image\\red.jpg"));  
          }else{
              roomColor2.setIcon(new javax.swing.ImageIcon(".\\src\\Image\\images.jpeg"));  
          }
          if (roomStatus3.getText().equals("2/2")){
              roomColor3.setIcon(new javax.swing.ImageIcon(".\\src\\Image\\red.jpg"));  
          }else{
              roomColor3.setIcon(new javax.swing.ImageIcon(".\\src\\Image\\images.jpeg"));  
          }
          if (roomStatus4.getText().equals("2/2")){
              roomColor4.setIcon(new javax.swing.ImageIcon(".\\src\\Image\\red.jpg"));  
          }else{
              roomColor4.setIcon(new javax.swing.ImageIcon(".\\src\\Image\\images.jpeg"));  
          }
          if (roomStatus5.getText().equals("2/2")){
              roomColor5.setIcon(new javax.swing.ImageIcon(".\\src\\Image\\red.jpg"));  
          }else{
              roomColor5.setIcon(new javax.swing.ImageIcon(".\\src\\Image\\images.jpeg"));  
          }
          
        }
        
        
    }
    
     boolean checkRoom(int roomNum){
        
        num = Integer.toString(roomNum);
        roomNo = "room" + num;
        
        status = LobbyService.loadLobbyStatus(roomNo);
          return checkStatus(status);
       

    }
    
     boolean checkStatus(String status){
          if (Integer.parseInt(status) <= 1 && Integer.parseInt(status) >= 0){
            return true;
        }else{
            return false;   
        }
     }
     
    void clickRoom(){

        LobbyService.enterRoom(roomNo, num, status);
                
//        this.setVisible(false);
        
//        open room1
        
    }
    
    public void removePlayer(){
        
//        test case not use
        
        for (int i = 1 ; i <= 5 ; i++){
        checkRoom(i);
        
        if (Integer.parseInt(status) > 0 && Integer.parseInt(status) < 3){
            LobbyService.exitRoom(roomNo, num, status);
         }
        
        }   
    }


}
